# 主色调蓝色： #0084ff
# hover：     #006bde
# onerror="javascript:this.src='{{ with $.Site.Params.cdnURL }}{{ . }}{{ end }}{{ $.Site.Params.defaultLogo }}'"

baseURL               = "https://hellogame.one/"
languageCode          = "zh-CN"
title                 = "HelloGame - 游知 - 游戏开发资源导航站"
theme                 = "webstack"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"	# 站点静态文件保存目录


[params]
    author        = "ITBOB"
    keywords      = "游戏，HelloGame，游知，游戏开发，游戏资源，游戏导航"
    description   = "HelloGame - 游知 - 游戏开发资源导航站"
    cdnURL        = "https://img.hellogame.one/"      # CDN 地址，置空则不使用 CDN
    cdnURLPubilc  = "https://img.hellogame.one/"         # CDN 地址，置空则不使用 CDN
    repository    = "https://github.com/GailZhangJY/HelloGame"    # 左侧导航栏的"GitHub"
    enablePreLoad = true					               # 网站完全打开前预加载动画
    textPreLoad   = "HelloGame加载中..."				   # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					               # 默认展开左侧边导航栏（已失效，默认不展开，会记住用户的行为，下次打开会保持）
    logosPath     = "logo"			                       # 网站每个导航地址logo存放地址
    defaultLogo   = "images/logo/default.png"		       # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					               # 默认站点为深色(夜间)模式
    yiyan         = true                         		   # 默认启用一言服务
    showArticle   = false					               # 默认显示最新文章

[params.seniverse]
    key = "a39cd5a0-4024-4cb2-85c6-0250317058db"

[params.images]
    favicon           = "web/logo.png"
    appleTouchIcon    = "web/logo.png"
    searchImageL      = "images/friends2.jpg"		# 搜索部分浅色背景图
    searchImageD      = "images/bg-dna.jpg"		    # 搜索部分深色背景图
    logoExpandLight   = "web/logo.png"
    logoExpandDark    = "web/logo.png"
    logoCollapseLight = "web/logo.png"
    logoCollapseDark  = "web/logo.png"

[params.info]
    email = "hellogame@zhangjy.me"
    emailHref = "mailto:hellogame@zhangjy.me"

[markup.goldmark.renderer]
    unsafe = true

[minify]
    minifyOutput = true
